import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Navbar from './components/Navbar';
import getCurrentUser from './actions/getCurrent';
import  Script  from 'next/script';
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
})
{
  const currentUser  = await getCurrentUser();
  return (
    <html lang="en">
      <body className={inter.className}>
          <Navbar currentUser={currentUser}/>
          {children}
          <Script
            type="text/javascript"
            src="//dapi.kakao.com/v2/maps/sdk.js?appkey=821a7ba786e3c679010d6bbfc29922a1&libraries=services,clusterer&autoload=false"
        ></Script>
        </body>
    </html>
  )
}
